---

version: "3"

services:

  biz_balance-mysql:
    build: ./mysql
    volumes:
      - /srv/mysql:/var/lib/mysql
    tty: true

  biz_balance-apache:
    build: ./apache
    ports:
      - 80:80
      - 443:443
    volumes:
      - /srv/www:/var/www/biz-balance
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    depends_on:
      - biz_balance-mysql
    links:
      - biz_balance-mysql:mysql
    tty: true
